name = "delosian"
pages_build_output_dir = "/public"

[[kv_namespaces]]
binding = "MY_KV"
id = "12035954d5f34578ab51022223570ffd"

#kv_namespaces = [
#  { id = "12035954d5f34578ab51022223570ffd", binding="MY_KV" }
#]

